## 1. 广铁查询异常处理

### 环境信息

```
clickhouse 
io.netty
```

### 问题

```
http://10.160.9.19:1180/bigdata-electric/v1/signal/mnl/getlz4?stationCode=GH000003&startTime=1546272060000&endTime=1546272060000 查询报错
```

### 根本原因

```
数据查询在clickhouse的执行时间超过4s后，应用端的读取超时规则生效，主动断开了连接，导致出错。
```

### 诊断步骤

```
1	java 堆栈如下：

11:20:20.304 [restartedMain] INFO  s.documentation.spring.web.readers.operation.CachingOperationNameGenerator - Generating unique operation named: typeUnionSqlUsingPOST_1
11:20:20.315 [restartedMain] INFO  s.documentation.spring.web.readers.operation.CachingOperationNameGenerator - Generating unique operation named: getUsingGET_3
11:20:20.364 [restartedMain] INFO  org.apache.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-1180"]
11:20:20.368 [restartedMain] INFO  org.apache.tomcat.util.net.NioSelectorPool - Using a shared selector for servlet write/read
11:20:20.399 [restartedMain] INFO  com.railway.bigdata.electric.platform.BigdataElectricPlatformApp - Started BigdataElectricPlatformApp in 5.618 seconds (JVM running for 6.085)
	。
	。	
	。
Caused by: com.netflix.client.ClientException: Number of retries on next server exceeded max 1 retries, while making a call for: 10.160.9.20:8123
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$4.call(LoadBalancerCommand.java:352)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$4.call(LoadBalancerCommand.java:345)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:77)
	... 56 more
Caused by: io.netty.handler.timeout.ReadTimeoutException

可以看到最下层抛异常的信息是ReadTimeoutException，从字面意思理解这是一个读取超时的异常，所属包名为io.netty

2 clickhouse 日志查看

2019.01.09 12:52:08.351660 [ 246 ] {} <Error> virtual DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse(): Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 42570, e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x568fcb6]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x29b94cf]
2. clickhouse-server(DB::WriteBufferFromOStream::nextImpl()+0xba) [0x56b93fa]
3. clickhouse-server(DB::WriteBufferFromHTTPServerResponse::nextImpl()+0x8e) [0x56b8c4e]
4. clickhouse-server(DB::WriteBufferFromHTTPServerResponse::finalize()+0x2a) [0x56b88aa]
5. clickhouse-server(DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse()+0x18) [0x56b8f18]
6. clickhouse-server(std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()+0xa2) [0x29ba2a2]
7. clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x50a) [0x29d3dfa]
8. clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x23e) [0x578824e]
9. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x57841ef]
10. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x110) [0x5784850]
11. clickhouse-server(Poco::PooledThread::run()+0x77) [0x583a197]
12. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x58374f8]
13. clickhouse-server() [0x5d9675f]
14. /lib64/libpthread.so.0(+0x7dc5) [0x7fdc23df7dc5]
15. /lib64/libc.so.6(clone+0x6d) [0x7fdc2361c73d]

从clickhouse看到异常出现在WriteBufferFromHTTPServerResponse函数这里：Cannot write to ostream at offset 42570，这很可能是响应http查询请求时，向缓冲区写入数据时连接异常断开所导致。

3.从java堆栈和clickhouse的日志上推测查询失败的原因是读取时连接超时主动断开。
	从网上搜索下java的io.netty包信息，官网介绍如下：
	Netty is an asynchronous event-driven network application framework 
	for rapid development of maintainable high performance protocol servers & clients
	是一款c/s架构的高性能异步事件驱动的网络通信开发框架，它的默认读取超时时间是4秒。
	而从实际查询的情况来看，出错的查询使用clickhouse客户端查询的耗时也基本都是超过4秒的，而客户端查询不超过   4秒的通过http应用查询时也不会出错。
4.应用端修改读取超时配置为30秒后，之前http查询出错的问题不再出现，问题解决。
```

## 2. 创建PostGIS报错

### 环境信息

```
Red Hat Enterprise Linux Server release 7.4 (Maipo)
PostgreSQL 10.4, FlyingDB 3.4EE, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16), 64
-bit
```

### 问题

```
test=# create extension postgis;

ERROR:  could not load library "/data/Flyingdb/3.4/08k/lib/postgresql/postgis-2.4.so": libgeos_c.so.1: cannot open shared object file: No such file or directory
```

### 根本原因

```
创建postgis时，因缺少库文件创建失败
```

### 诊断步骤

```sql
1、根据报错信息在/data/Flyingdb/3.4/08k/lib目录下查找libgeos_c.so.1文件，并未发现该文件

2、切换root用户在所有目录下进行查找libgeos_c.so.1文件，用find命令搜索“libgeos_c.so.1”文件
[root@localhost ~]#  find / -name libgeos_c.so.1
/data/Flyingdb/3.4/08k/plugin/geos/lib/libgeos_c.so.1

3、发现libgeos_c.so.1文件在/data/Flyingdb/3.4/08k/plugin/geos/lib目录下，查看是否将该目录链接到共享库中
[root@localhost ~]# cat /etc/ld.so.conf.d/geos-3.6.3.conf 
/data/Flyingdb/3.4/08k/plugin/geos/lib

4、发现该目录已配置好，将其生效并进行查看是否在共享库中存在
[root@localhost ~]# ldconfig
[root@localhost ~]# ldconfig -p|grep "libgeos_c.so.1"

5、经过操作并未生效，此后将libgeos_c.so.1文件复制到数据库安装目录的lib文件夹中
[root@localhost ~]# cp /data/Flyingdb/3.4/08k/plugin/geos/lib/libgeos_c.so.1 /data/Flyingdb/3.4/08k/lib

6、对复制的文件进行属主属组的修改
[root@localhost ~]# chown postgres. /data/Flyingdb/3.4/08k/lib/libgeos_c.so.1

7、将其生效，并查看
[root@localhost ~]# ldconfig
[root@localhost ~]# ldconfig -p|grep "libgeos_c.so.1" libgeos_c.so.1 (libc6,x86-64) => /data/Flyingdb/3.4/08k/lib/libgeos_c.so.1

8、登录数据库进行测试
test=# create extension postgis;
CREATE EXTENSION
```

## 3. 候补队列磁盘空间不足处理案例

### 环境信息

```
Red Hat Enterprise Linux (RHEL) 7.4
fd_mqextractor (FlyingDB) 3.1EE
```

### 问题

```
候补队列10.2.211.13磁盘空间不足
```

### 根本原因

```
10.2.211.13上部署的fd_mqextractor数据传输工具产生了大量日志，没有及时清除
```

###  处理步骤

```
1.由于13和16部署的postgres数据库是测试环境，选择关闭10.2.211.13和10.2.211.16的fd_mqextractor进程，并清理fd_mqextractor日志。
```

```
2.由于生产环境10.2.211.10上也部署了fd_mqextractor程序，为了防止日志清理不及时造成相同的磁盘空间不足问题发生，在10.2.211.10上部署一个定时清除日志的脚本，如下：
```

```
#!/bin/bash
#打包压缩前一天的日志，清除七天前的日志
#DATE当前日期，DATE_1前一天日期，DATE_7七天前日期

export DATE=$(date +"%Y%m%d")
export DATE_1=$(date --date "1 days ago" +"%Y%m%d")
export DATE_7=$(date --date "7 days ago" +"%Y%m%d")
export LOG_DIR=/home/postgres/flyingdb-v3std-20171120/08k/fd_mqextractor_log

cd ${LOG_DIR:?var is empty}
tar -zcvf pg2rabbitmq.${DATE_1:?var is empty}.tar.gz ./pg2rabbitmq.${DATE_1:?var is empty}*.log --remove-files

test -f $LOG_DIR/pg2rabbitmq.${DATE_7:?var is empty}.tar.gz
    if [ $? -eq 0 ]; then
        rm -f pg2rabbitmq.${DATE_1:?var is empty}*
    fi
```

## 4. This ZooKeeper instance is not currently serving requests

### 环境信息

```
CentOS Linux release 7.3.1611 (Core) 
psql (PostgreSQL) 10.4
zookeeper-3.4.10
```

###  问题

```
三台zookeeper节点均启动之后，查看状态报错。
用telnet工具连接zookeeper查看状态，出现“This ZooKeeper instance is not currently serving requests”的报错输出。
```

###  根本原因

```
上网查询“This ZooKeeper instance is not currently serving requests”异常报错的原因，是因为没有选出leader。检查操作步骤过程，发现漏操作关闭防火墙这一步，而启动的防火墙也没有开放2181、2888、3888端口。服务起了，但三个zookeeper节点之间无法网络互通，所以没有选出leader。
```

###  诊断步骤

```shell
#三台zookeeper节点均启动之后，查看状态，出现报错。
[postgres@test1 ~]$ /home/postgres/data/tools/zookeeper/bin/zkServer.sh status
ZooKeeper JMX enabled by default
Using config: /home/postgres/data/tools/zookeeper/bin/../conf/zoo.cfg
Error contacting service. It is probably not running.

#ps查看是否存在zookeeper进程
[postgres@test1 ~]$ ps -ef | grep zookeeper
postgres   2288      1  0 17:09 pts/0    00:00:06 /home/postgres/data/tools/jdk1.8.0_161/bin/java -Dzookeeper.log.dir=. -Dzookeeper.root.logger=INFO,CONSOLE -cp /home/postgres/data/tools/zookeeper/bin/../build/classes:/home/postgres/data/tools/zookeeper/bin/../build/lib/*.jar:/home/postgres/data/tools/zookeeper/bin/../lib/slf4j-log4j12-1.6.1.jar:/home/postgres/data/tools/zookeeper/bin/../lib/slf4j-api-1.6.1.jar:/home/postgres/data/tools/zookeeper/bin/../lib/netty-3.10.5.Final.jar:/home/postgres/data/tools/zookeeper/bin/../lib/log4j-1.2.16.jar:/home/postgres/data/tools/zookeeper/bin/../lib/jline-0.9.94.jar:/home/postgres/data/tools/zookeeper/bin/../zookeeper-3.4.10.jar:/home/postgres/data/tools/zookeeper/bin/../src/java/lib/*.jar:/home/postgres/data/tools/zookeeper/bin/../conf:.:/home/postgres/data/tools/jdk1.8.0_161/lib.tools.jar -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false org.apache.zookeeper.server.quorum.QuorumPeerMain /home/postgres/data/tools/zookeeper/bin/../conf/zoo.cfg
postgres   2465   2402  0 17:39 pts/0    00:00:00 grep --color=auto zookeeper

#用telnet工具连接zookeeper查看状态
[root@test1 ~]# telnet 127.0.0.1 2181
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
stat
This ZooKeeper instance is not currently serving requests
Connection closed by foreign host.

#在防火墙中添加2181、2888、3888端口
firewall-cmd --zone=public --add-port=2181/tcp --permanent
firewall-cmd --zone=public --add-port=2888/tcp --permanent
firewall-cmd --zone=public --add-port=3888/tcp --permanent
firewall-cmd --reload

#再次查看状态
[postgres@test1 ~]$ /home/postgres/data/tools/zookeeper/bin/zkServer.sh status
ZooKeeper JMX enabled by default
Using config: /home/postgres/data/tools/zookeeper/bin/../conf/zoo.cfg
Mode: follower
```

## 5. 带有更新语句的bug

### 环境信息

```
Red Hat Enterprise Linux Server release 6.8 (Santiago)
PostgreSQL 10.4, FlyingDB 3.4EE, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16), 64-bit
```

### 问题

```
带有更新语句的bug
```

### 根本原因

```
多赋值的实现认为引用多赋值子计划的输出的参数将与该多赋值的子计划节点出现在相同的目标列中。这在顺序扫描的目标列中是有效的，但是结果有相同参数的另一个出现，而这个参数是错位的。这是因为fix_upper_expr_mutator按错误的顺序执行操作，导致它发出一个裸参数，而它应该发出一个引用来自下平面节点的参数输出的变量。
```

### 诊断步骤

```
CREATE TABLE t11 (a VARCHAR(1));
CREATE TABLE t22 (b VARCHAR(1));
INSERT INTO t11 VALUES ('A');
INSERT INTO t22 VALUES ('A');
UPDATE t11 SET (a) = (SELECT b FROM t22 WHERE t22.b = t11.a) WHERE 'X' NOT IN ('Y', 'Z');

执行以上语句结果报错如下：
flying=# UPDATE t11 SET (a) = (SELECT b FROM t22 WHERE t22.b = t11.a) WHERE 'X' NOT IN ('Y', 'Z');
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 

log日志如下：
2019-01-19 16:03:30.042 CST,,,1909,,5c388972.775,11,,2019-01-11 20:17:54 CST,,0,LOG,00000,"server process (PID 3445) was terminated by signal 11: Segmentation fault","Failed process was running: UPDATE t11 SET (a) = (SELECT b FROM t22 WHERE t22.b = t11.a) WHERE 'X' NOT IN ('Y', 'Z');",,,,,,,"LogChildExit, postmaster.c:3663",""
2019-01-19 16:03:30.042 CST,,,1909,,5c388972.775,12,,2019-01-11 20:17:54 CST,,0,LOG,00000,"terminating any other active server processes",,,,,,,,"HandleChildCrash, postmaster.c:3383",""
2019-01-19 16:03:30.043 CST,,,3439,,5c42d815.d6f,1,,2019-01-19 15:56:05 CST,1/0,0,WARNING,57P02,"terminating connection because of crash of another server process","The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.","In a moment you should be able to reconnect to the database and repeat your command.",,,,,,"quickdie, postgres.c:2589",""
2019-01-19 16:03:30.044 CST,,,3516,"[local]",5c42d9d2.dbc,1,"",2019-01-19 16:03:30 CST,,0,LOG,00000,"connection received: host=[local]",,,,,,,,"BackendInitialize, postmaster.c:4309",""
2019-01-19 16:03:30.044 CST,"flying","flying",3516,"[local]",5c42d9d2.dbc,2,"",2019-01-19 16:03:30 CST,,0,FATAL,57P03,"the database system is in recovery mode",,,,,,,,"ProcessStartupPacket, postmaster.c:2300",""
2019-01-19 16:03:30.045 CST,,,1909,,5c388972.775,13,,2019-01-11 20:17:54 CST,,0,LOG,00000,"all server processes terminated; reinitializing",,,,,,,,"PostmasterStateMachine, postmaster.c:3907",""
2019-01-19 16:03:30.117 CST,,,3517,,5c42d9d2.dbd,1,,2019-01-19 16:03:30 CST,,0,LOG,00000,"database system was interrupted; last known up at 2019-01-19 15:56:05 CST",,,,,,,,"StartupXLOG, xlog.c:6269",""
2019-01-19 16:03:30.162 CST,,,3517,,5c42d9d2.dbd,2,,2019-01-19 16:03:30 CST,,0,LOG,00000,"database system was not properly shut down; automatic recovery in progress",,,,,,,,"StartupXLOG, xlog.c:6772",""
2019-01-19 16:03:30.164 CST,,,3517,,5c42d9d2.dbd,3,,2019-01-19 16:03:30 CST,,0,LOG,00000,"redo starts at C/BFCD5860",,,,,,,,"StartupXLOG, xlog.c:7027",""
2019-01-19 16:03:30.204 CST,,,3517,,5c42d9d2.dbd,4,,2019-01-19 16:03:30 CST,,0,LOG,00000,"invalid record length at C/BFCE1C28: wanted 24, got 0",,,,,,,,"ReadRecord, xlog.c:4191",""
2019-01-19 16:03:30.204 CST,,,3517,,5c42d9d2.dbd,5,,2019-01-19 16:03:30 CST,,0,LOG,00000,"redo done at C/BFCE1BF0",,,,,,,,"StartupXLOG, xlog.c:7299",""
2019-01-19 16:03:30.204 CST,,,3517,,5c42d9d2.dbd,6,,2019-01-19 16:03:30 CST,,0,LOG,00000,"last completed transaction was at log time 2019-01-19 16:01:43.912202+08",,,,,,,,"StartupXLOG, xlog.c:7304",""
2019-01-19 16:03:30.217 CST,,,3517,,5c42d9d2.dbd,7,,2019-01-19 16:03:30 CST,,0,LOG,00000,"checkpoint starting: end-of-recovery immediate",,,,,,,,"LogCheckpointStart, xlog.c:8387",""
2019-01-19 16:03:30.227 CST,,,3517,,5c42d9d2.dbd,8,,2019-01-19 16:03:30 CST,,0,LOG,00000,"checkpoint complete: wrote 23 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.002 s, sync=0.000 s, total=0.010 s; sync files=18, longest=0.000 s, average=0.000 s; distance=49 kB, estimate=49 kB",,,,,,,,"LogCheckpointEnd, xlog.c:8469",""
2019-01-19 16:03:30.230 CST,,,1909,,5c388972.775,14,,2019-01-11 20:17:54 CST,,0,LOG,00000,"database system is ready to accept connections",,,,,,,,"reaper, postmaster.c:2973",""

操作系统日志如下：
Jan 19 16:03:29 redhat68 kernel: postgres[3445]: segfault at 8 ip 000000000047cdd8 sp 00007fff9a4daaf0 error 4 in postgres[400000+68b000]
Jan 19 16:03:30 redhat68 abrt[3513]: Saved core dump of pid 3445 (/home/postgres/FlyingDB/3.1/08k/bin/postgres) to /var/spool/abrt/ccpp-2019-01-19-16:03:29-3445 (580579328 bytes)
Jan 19 16:03:30 redhat68 abrtd: Directory 'ccpp-2019-01-19-16:03:29-3445' creation detected
Jan 19 16:03:30 redhat68 abrtd: Executable '/home/postgres/FlyingDB/3.1/08k/bin/postgres' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Jan 19 16:03:30 redhat68 abrtd: 'post-create' on '/var/spool/abrt/ccpp-2019-01-19-16:03:29-3445' exited with 1
Jan 19 16:03:30 redhat68 abrtd: Deleting problem directory '/var/spool/abrt/ccpp-2019-01-19-16:03:29-3445'

执行计划如下：
flying=# explain UPDATE t11 SET (a) = (SELECT b FROM t22 WHERE t22.b = t11.a) WHERE 'X' NOT IN ('Y', 'Z');
                               QUERY PLAN                                
-------------------------------------------------------------------------
 Update on t11  (cost=0.00..86477.60 rows=2260 width=46)
   ->  Result  (cost=0.00..86477.60 rows=2260 width=46)
         One-Time Filter: ('X'::text <> ALL ('{Y,Z}'::text[]))
         ->  Seq Scan on t11  (cost=0.00..86477.60 rows=2260 width=46)
               SubPlan 1 (returns $1)
                 ->  Seq Scan on t22  (cost=0.00..38.25 rows=11 width=8)
                       Filter: ((b)::text = (t11.a)::text)
(7 rows)

flying=#

解决方法如下：
1、将 "SET (a) = " 换成 "SET a = "可以执行成功：
flying=# UPDATE t11 SET a = (SELECT b FROM t22 WHERE t22.b = t11.a) WHERE 'X' NOT IN ('Y', 'Z');
UPDATE 1

2、将where子句去掉可以执行成功：
flying=# UPDATE t11 SET (a) = (SELECT b FROM t22 WHERE t22.b = t11.a);
UPDATE 1

3、将 SELECT b FROM t2 WHERE t2.b = t1.a 换成 SELECT b FROM t2 WHERE t2.b = 'A' 可以执行成功：
flying=# UPDATE t11 SET (a) = (SELECT b FROM t22 WHERE t22.b = 'A') WHERE 'X' NOT IN ('Y', 'Z'); 
UPDATE 1
```

### 参考链接

<https://www.postgresql-archive.org/segmentation-fault-with-simple-UPDATE-statement-postgres-10-5-td6062572.html>